apiVersion: v1
kind: Service #It isn't a deployment it is a service
metadata:
  name: platformnpservice-srv #np for node port
spec: 
  type: NodePort
  selector:
    app: platformservice #select the platformservice name
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80 #where to connect to and what port to connect to it