# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Add testing.
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Build project
      run: npm run build
