# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Add testing.
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./web

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.0
        cache: 'npm'
    - name: Installing dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Building
      run: npm run build --if-present
      working-directory: ${{env.working-directory}}
